server {
    host = "localhost"
    port = 8080
}

vk {
    token = "5762321640f2e234995b3d4deb7cf2f66f3f38f5336ae2c63b24105a630265edd200c7635f8803955a8ea"
}

postgres {
    jdbc-url = "jdbc:postgresql://localhost:5432/testdb"
    username = "testuser"
    password = "password"
}