server {
    host = "0.0.0.0"
    port = 8080
    port = ${?SERVER_PORT}
}

vk {
    token = "changeme"
    token = ${?VK_TOKEN}
}

postgres {
    jdbc-url = "jdbc:postgresql://localhost:5432/pangea"
    jdbc-url = ${?POSTGRES_JDBC_URL}
    username = "pangea"
    username = ${?POSTGRES_USER}
    password = "pangea"
    password = ${?POSTGRES_PASSWORD}
}